# Remember to check that the build does not interfere with the memory declared here!


[Code]
cstack = $7ff
# Rolling buffer for the decompress and EOR part. Must be at the beginning of a page!
rollingbuffer = $200
CustomChargen = $d000
ScreenUnderIO = $d800


[Arc]
# We need two more screens as this effect may be in quick succession after the others...
Screen0 = $c000
Screen1 = $c400


[RNR]
Bordercolour = 6
Textcolour = 6
Fontaddress = $d000
Screen0 = $c800
Screen1 = $cc00
Width = 59
Height = 44
DisplayTime = 50*15

[GFX]
BitmapAddr = $e000
HiScreenAddr = $dc00
Bordercolour = 6
Foreground = 6
Background = 1
DisplayTime = 50*20

[Smiley]
Runtime = 50*10

[Greetings]
skip_every = 2
screen = $c400
