  .byte 0, 21
  scrcode "abyss connection"
  .byte 0, 38
  scrcode "atlantis"
  .byte 0, 43
  scrcode "blazon"
  .byte 0, 35
  scrcode "classic videogames radio"
  .byte 0, 27
  scrcode "commodore treffen graz"
  .byte 0, 32
  scrcode "cosmos designs"
  .byte 0, 39
  scrcode "delysid"
  .byte 0, 38
  scrcode "digital talk team"
  .byte 0, 39
  scrcode "excess"
  .byte 0, 42
  scrcode "fairlight"
  .byte 0, 43
  scrcode "padua"
  .byte 0, 43
  scrcode "rabenauge"
  .byte 0, 40
  scrcode "the solution"
  .byte 0, 41
  scrcode "triad"
  .byte 0, 45
  scrcode "gloegg"
  .byte 0, 43
  scrcode "harekiet"
  .byte 0, 43
  scrcode "coyhot"
  .byte 0, 42
  scrcode "jasmin68k"
  .byte 0, 43
  scrcode "phiwa"
  .byte 0, 45
  scrcode "sissim"
  .byte 0, 45
  scrcode "joe"
  .byte 0, 47
  scrcode "jok"
  .byte 0, 45
  scrcode "nodepond"
  .byte 0, 40
  scrcode "wizball6502"
  .byte 0, 43
  scrcode "xxx"
  .byte 0, 70
  .byte 0,0
