NextText " \x1e wizball6502        \x99  commodore treffen graz          trex          delysid                         ", 3, 6
NextText "  \x99 rebels          joe          quantum      \x1f    the solution          hokuto force                         ", 8, 6
NextText " \x1e gorgh          abyss connection          cpc user club          atlantis                         ", 13, 6
NextText "   \x1e blazon          excess          gloegg     \x96     haujobb        \x95  padua                         ", 18, 6
NextText " \x1e coyhot          laxity          onslaught          finnish gold          phiwa                         ", 23, 6
NextText "  \x1e genesis project       \x95   xxx          triad          classic videogames radio                         ", 28, 6
NextText " \x9e jasmin68k          nodepond        \x1e  digital talk team          harekiet                         ", 33, 6
NextText "    \x1e rabenauge          fairlight          sissim          cosmos designs                         ", 38, 6
