IRQRASTERLINE = 50

	.export set_irq
	.import muzak_play

	.bss
oldirq:	.res	2

	.code
irq:
	.ifdef DEBUG
	inc	$d020
	.endif
	jsr	muzak_play
	.ifdef DEBUG
	dec	$d020
	.endif
;	;;
;	ldy	#3
;@l:	lda	$dc08,y
;	sta	$0400,y
;	dey
;	bpl	@l
	asl	$d019		; Acknowledge IRQ
	jmp	(oldirq)

	.code
set_irq:
	lda	$314
	sta	oldirq
	lda	#<irq
	sta	$314
	lda	$314+1
	sta	oldirq+1
	lda	#>irq
	sta	$315
	lda	#<IRQRASTERLINE
	sta	$d012
	lda	$d011
	and	#$7f
	sta	$d011
	lda #$7f
        sta $dc0d       ;disable timer interrupts which can be generated by the two CIA chips
        sta $dd0d       ;the kernal uses such an interrupt to flash the cursor and scan the keyboard,
                        ;so we better stop it.
        lda $dc0d       ;by reading this two registers we negate any pending CIA irqs.
        lda $dd0d       ;if we don't do this, a pending CIA irq might occur after we finish setting up our irq.
                        ;we don't want that to happen.
        lda #$01        ;this is how to tell the VICII to generate a raster interrupt
        sta $d01a
	cli
	rts

