;
; File generated by cc65 v 2.16 - Ubuntu 2.16-2
;
	.fopt		compiler,"cc65 v 2.16 - Ubuntu 2.16-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "linked_list.c", 499, 1585557270
	.dbg		file, "/usr/share/cc65/include/stdio.h", 6186, 1510859474
	.dbg		file, "/usr/share/cc65/include/stddef.h", 3057, 1510859474
	.dbg		file, "/usr/share/cc65/include/stdarg.h", 2913, 1510859474
	.dbg		file, "/usr/share/cc65/include/stdlib.h", 5748, 1510859474
	.forceimport	__STARTUP__
	.dbg		sym, "malloc", "00", extern, "_malloc"
	.dbg		sym, "free", "00", extern, "_free"
	.import		_malloc
	.import		_free
	.export		_add_one
	.export		_main

; ---------------------------------------------------------------
; __near__ struct LinkedList * __near__ add_one (__near__ struct LinkedList *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_one: near

	.dbg	func, "add_one", "00", extern, "_add_one"
	.dbg	sym, "begin", "00", auto, 0
	.dbg	sym, "curr", "00", auto, -2

.segment	"CODE"

	.dbg	line, "linked_list.c", 9
	jsr     pushax
	.dbg	line, "linked_list.c", 10
	jsr     pushw0sp
	.dbg	line, "linked_list.c", 12
L0003:	jsr     ldax0sp
	jsr     pushax
	ldy     #$05
	jsr     ldeaxidx
	ldy     #$01
	jsr     inceaxy
	ldy     #$02
	jsr     steaxspidx
	.dbg	line, "linked_list.c", 13
	jsr     ldax0sp
	jsr     ldaxi
	jsr     stax0sp
	.dbg	line, "linked_list.c", 14
	ldy     #$02
	cmp     (sp),y
	bne     L0003
	txa
	iny
	cmp     (sp),y
	bne     L0003
	.dbg	line, "linked_list.c", 15
	jsr     ldax0sp
	.dbg	line, "linked_list.c", 16
	jmp     incsp4
	.dbg	line

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "beginptr", "00", auto, -2

.segment	"CODE"

	.dbg	line, "linked_list.c", 21
	jsr     decsp2
	ldx     #$00
	lda     #$06
	jsr     _malloc
	jsr     stax0sp
	.dbg	line, "linked_list.c", 22
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	ldy     #$00
	sta     (sreg),y
	iny
	txa
	sta     (sreg),y
	.dbg	line, "linked_list.c", 23
	jsr     pushw0sp
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$02
	jsr     steaxspidx
	.dbg	line, "linked_list.c", 24
	jsr     ldax0sp
	jsr     _add_one
	.dbg	line, "linked_list.c", 25
	jsr     ldax0sp
	jsr     _free
	.dbg	line, "linked_list.c", 26
	ldx     #$00
	txa
	.dbg	line, "linked_list.c", 27
	jmp     incsp2
	.dbg	line

.endproc

